### ISSUE TITLE
7.0系统会报异常，handler给DeadThread 发送消息

### ISSUE THREAD

**Issue by autoool** [ronghao/AutoScrollTextView#2]
你好，7.0 系统会报异常，造成空白
![image](https://user-images.githubusercontent.com/8943761/34805159-8ef80bbc-f6b7-11e7-939e-30156c4c1c2f.png)

**Comment by ronghao** [comment]
@chaozaiai 
我在7.0系统测试通过。
该问题出现在该示例工程，还是你的工程中？
能具体描述下使用场景吗？
