### ISSUE TITLE
一个页面放两个有一个会在某一时刻莫名其妙的不动了

### ISSUE THREAD

**Issue by BaoTaoGitHub** [ronghao/AutoScrollTextView#3]
如题

**Comment by BaoTaoGitHub** [comment]
我也遇见了这个问题了，这个控件不适合放两个感觉。还有一个问题是，放两个控件在同一页面会出现 当某一个控件上下翻转的时候，左右滚动的那个控件就会卡顿一下，。

**Comment by ronghao** [comment]
提供一下手机型号，android版本等信息，方便排查

**Comment by BaoTaoGitHub** [comment]
三星S8，android7.0，大神，运行你这个demo也会出现卡顿，你可以仔细观察一下。谢谢了

**Comment by ronghao** [comment]
更新新版本，1.0.2，查看是否解决
